name: Build and Execute Benchmark tests

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: self-hosted

    strategy:
      max-parallel: 1
      matrix:
        flags:
          - "--use-verbose --use-prod --width=200 --height=200"
          - "--use-verbose --use-prod --width=400 --height=400"

    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout Pendulum Simulation
      uses: actions/checkout@v2
      with:
        path: v-pendulum-simulation
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Install Dependencies
      run: sudo apt install --quiet -y --no-install-recommends libgc-dev
    - name: Move Pendulum Simulation source code to V Modules
      run: mv ./v-pendulum-simulation ~/.vmodules
    - name: Execute Tests
      run: |
        cd ~/.vmodules/v-pendulum-simulation
        ./bin/run-benchmark-test ${{ matrix.flags }}
