name: Build and Execute Benchmark tests

on:
  push:
    branches:
      - main

jobs:
  ubuntu:
    runs-on: ubuntu-latest

  strategy:
    matrix:
      flags:
        - "--width=200 --height=200"
        - "--wtdth=400 --height=400"

  steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - name: Checkout Pendulum Simulation
      uses: actions/checkout@v2
      with:
        path: v-pendulum-simulation
    - name: Build V
      run: |
        make
        sudo ./v symlink
    - name: V doctor
      run: v doctor
    - name: Move Pendulum Simulation source code to V Modules
      run: mv ./v-pendulum-simulation ~/.vmodules
    - name: Execute Tests
      run: ~/.vmodules/v-pendulum-simulation/bin/run-benchmark-test ${{ matrix.flags }}
