name: Build and Execute Benchmark tests

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  linux:
    runs-on: self-hosted

    strategy:
      max-parallel: 1
      matrix:
        flags:
          - "--use-prod --width=200 --height=200"
          - "--use-prod --width=400 --height=400"
          - "--use-prod --use-gc=boehm --width=200 --height=200"
          - "--use-prod --use-gc=boehm --width=400 --height=400"

    steps:
    - name: Checkout Latest V
      uses: actions/checkout@v2
      with:
        repository: vlang/v

    - name: Checkout Pendulum Simulation
      uses: actions/checkout@v2
      with:
        path: v-pendulum-simulation

    - name: Build V
      run: |
        make
        sudo ./v symlink

    - name: V doctor
      run: v doctor

    - name: Execute Tests
      run: ./v-pendulum-simulation/bin/run-benchmark-test ${{ matrix.flags }}

    - name: Create artifact with execution logs
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: logs
        path: /tmp/*.log
