name: Build and Execute Benchmark tests

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  linux:
    runs-on: self-hosted

    strategy:
      max-parallel: 1
      matrix:
        flags:
          - "--use-prod --use-gc=boehm --times=5 --width=100 --height=100"
          - "--use-prod --use-gc=boehm --times=5 --width=150 --height=150"
          - "--use-prod --use-gc=boehm --times=5 --width=200 --height=200"
          - "--use-prod --use-gc=boehm --times=5 --width=300 --height=300"
          - "--use-prod --use-gc=boehm --times=5 --width=400 --height=400"
          - "--use-prod --use-gc=boehm --times=5 --width=600 --height=600"
          - "--use-prod --use-gc=boehm --times=5 --width=800 --height=800"
          - "--use-prod --use-gc=boehm --times=5 --width=1000 --height=1000"

    steps:
      - name: Checkout Latest V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Checkout Pendulum Simulation
        uses: actions/checkout@v2
        with:
          path: v-pendulum-simulation

      - name: Build and Install V
        run: |
          if ! type -p v >/dev/null; then
            make
            sudo ./v symlink
          fi
          v up

      - name: V doctor
        run: v doctor

      - name: Execute Tests with Flags ${{ matrix.flags }} 5 times
        run: |
          ./v-pendulum-simulation/bin/run-benchmark-test --sequential-only ${{ matrix.flags }}
          for jobs in 0 1 2 3 4 6; do
            ./v-pendulum-simulation/bin/run-benchmark-test --parallel-only --jobs=${jobs} ${{ matrix.flags }}
          done

      - name: Create artifact with execution logs
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: logs
          path: ./v-pendulum-simulation/simulation_log_*.log
